//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public string MaVe { get; set; }
        public string MaDH { get; set; }
        public string MaLoaiVe { get; set; }
        public string TenVe { get; set; }
        public string MaSK { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual LoaiVe LoaiVe { get; set; }
        public virtual SuKien SuKien { get; set; }
    }
}
